-- AlterTable
ALTER TABLE `user` ADD COLUMN `mustChangePassword` BOOLEAN NOT NULL DEFAULT true,
    MODIFY `role` ENUM('COMPANY_ADMIN', 'HR_ADMIN', 'COMPANY_REP', 'FLEET_SUPERINTENDENT', 'OPERATIONS_MANAGER', 'CAPTAIN', 'CHIEF_MATE', 'CHIEF_ENGINEER', 'SECOND_ENGINEER', 'SHIP_CREW', 'SAFETY_OFFICER', 'COMPANY_EMPLOYEE', 'PORT_OFFICIAL') NULL DEFAULT 'COMPANY_EMPLOYEE';
